parameters:
  name: ''
  vmImage: ''

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      maxParallel: 2
      matrix:
        php-7-1:
          phpVersion: 7.1
        php-7-2:
          phpVersion: 7.2
        php-7-3:
          phpVersion: 7.3
        php-7-4:
          phpVersion: 7.4
        php-8-0:
          phpVersion: 8.0
        php-8-1:
          phpVersion: 8.1
        php-8-2:
          phpVersion: 8.2
    steps:
      - script: |
          sudo update-alternatives --set php /usr/bin/php$(phpVersion)
          sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
          sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
          sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
          sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
          php -version
        displayName: 'Use PHP version $(phpVersion)'

      - script: composer install --no-interaction --prefer-dist
        displayName: 'composer install'

      - script: |
          vendor/bin/phpunit --log-junit $(Build.SourcesDirectory)/reports/TEST-phpunit-junit.xml
        displayName: 'Running Unit tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/TEST-*.xml'
          mergeTestResults: true
        displayName: 'Publish tests results'
