# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  branches:
    include:
      - refs/heads/*
    exclude:
      - refs/tags/*
      - README.md
      - LICENSE

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: 7.1

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: |
    vendor/bin/php-cs-fixer fix --dry-run
  displayName: 'Running PHP CS fixer'

- script: |
    vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit $(Build.SourcesDirectory)/reports/TEST-phpunit-junit.xml
  displayName: 'Running Unit tests and generating coverage report'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    mergeTestResults: true
  displayName: 'Publish tests results'

- bash: |
    bash <(curl -s https://codecov.io/bash) -t $(CODECOV_TOKEN)
  displayName: 'Upload coverage to codecov.io'
