name: Documentation

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: wget
        uses: wei/wget@v1
        with:
          args: -O phpDocumentor.phar https://phpdoc.org/phpDocumentor.phar

      - name: Generate the docs locally in CI
        run: php phpDocumentor.phar -d src

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .phpdoc/build
